### ISSUE TITLE
Docker 22.4 images in past few days are broken - builds done last week work great

### ISSUE THREAD

**Issue by itiligent** [greenbone/greenbone-container-images#1]
I've been using GVM for a year or so and I recently moved my company over to a docker based system. This system was built using the docker script supplied by Greenbone on the comminuty containers site and it has worked great.

We have previously built around 20 systems using the script, but in the last few days something has changed with the compose file and a bunch more containers have are now being pulled down. 

In the past few days GVM seems a bit less stable (another post for another day) but most importantly ANY NEW BUILD no longer applies credential scanning if configured.  Builds only a few weeks older perform credential scans no problem will show in their logs the status of the credentials too. Test builds today do not even acknowledge existend of or any attempts to use credentials - its as though they dont exist!  

We keep an unpatched Win10 1809 to verify all our pentest tools, and when this is lab scanned with another build from last week it  all works fine. (Also tested with GVM VMware appliance too.) If I roll back to a fresh Ubuntu snapshot on the same virutual machine as used for the earlier succesful tests, and then build with today's containers into the eact same network enviroment I can reproduce the same problem of no credentials scanning being avalaible anymore.

Any ideas what changed this week?

**Comment by bjoernricks** [comment]
Hi,

first of all thanks for letting us know about the issue. I suppose you are also the author of https://forum.greenbone.net/t/latest-docker-22-4-worked-great-last-week-now-is-suddenly-unstable-and-broken/12941 ?

**Comment by itiligent** [comment]
Hi Bjorn

Yes, its the same person. I was not sure where to post

If you need any extra info please just ask.

Thankyou

David Harrop (Australia GMT+10)

**Comment by itiligent** [comment]
I also forgot to mention something that might be related :

the documentation on the community containers site has changed in the last few days and the script reports missing apt package docker-compose.

Docker-compose was a listed dependency a few weeks back, but without it the setup script instructions can’t work.

Let me know if you need help to reproduce

**Comment by bjoernricks** [comment]
Not sure what you mean. docker-compose is still required https://greenbone.github.io/docs/latest/22.4/container/index.html#installing-docker-compose and https://github.com/greenbone/docs/blob/main/src/_static/setup-and-start-greenbone-community-edition.sh#L38 We have just raised the requirement to 1.27.0 or later which isn't available in Debian Bullseye. Therefore the installation method in the docs has changed to use `pip` (the Python package installer).

See https://greenbone.github.io/docs/latest/changelog.html for the changes in the docs.

**Comment by bjoernricks** [comment]
I am closing here now and put the discussion at https://forum.greenbone.net/t/latest-docker-22-4-worked-great-last-week-now-is-suddenly-unstable-and-broken/12941
