### ISSUE TITLE
redis-server does not work properly in the latest image after update to debian 12

### ISSUE THREAD

**Issue by dhedberg** [greenbone/greenbone-container-images#7]
The redis configuration has persistence turned on, which results in error message like:
```
12 Jun 2023 08:16:20.177 * Background saving started by pid 10
12 Jun 2023 08:16:20.177 # Failed opening the temp RDB file temp-10.rdb (in server root dir /) for saving: Permission denied
12 Jun 2023 08:16:20.231 # Background saving error
```

This does not seem to be a new issue as far as I can tell, what apparently is new is that redis 7 in debian 12 seems to stop working when it fails to store the data. This is possibly related to https://github.com/redis/redis/pull/10504

A workaround is to disable persistence like in https://github.com/greenbone/openvas-scanner/commit/aed047485f35a341ec75575a65f050fee5b74c12

We're running this in kubernetes, but I don't see any volume specified in the community docker compose configuration except for the socket. Running the image locally with podman results in the same issue (after a SET and an explicit SYNC).

**Comment by bjoernricks** [comment]
Thanks for letting us know. Should be fixed now.
